# Generated by Django 5.1.4 on 2025-01-15 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_comments_id_alter_post_id_alter_postvariant_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='text',
            new_name='comment_text',
        ),
        migrations.RenameField(
            model_name='postvariant',
            old_name='text',
            new_name='variant_text',
        ),
    ]
